org: jimuelpalaca
app: hapi
service: hapi
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
functions:
  api:
    handler: dist/app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
